[package]
name = "momento_cache_facade"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hello_momento_cache"
path = "src/bin/hello.rs"

[dependencies]
colog = "1.3.0"
dotenv = "0.15.0"
momento = "0.43.0"
tokio = { version = "1.40.0", features = ["full"] }
log = "0.4.22"
